name: main
on:
  push:
    bracnhes:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - name: verify
        run: make verify
      - name: test
        run: make test
      - name: build
        run: make build

