name: master
run-name: master
on: [pull_request] 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - run: make test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: make build
